---
title: "Getting started with Logger"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with Logger}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    fig.align = "center",
    fig.width = 12,
    fig.height = 10,
    dpi = 150,
    collapse = TRUE,
    comment = "#>"
)
```

## Introduction

The `Logger` package provides a flexible and customizable logging system for R applications. It allows developers to easily add logging capabilities to their projects, with features such as multiple log levels, file output, and custom formatting.

## Installation

You can install the `Logger` package from GitHub using the `devtools` package:

```r
# install.packages("devtools")
devtools::install_github("DereckmezquITA/Logger")
```

## Basic Usage

To get started with `Logger`, first load the package:

```r
library(Logger)
```

### Creating a Logger

You can create a new logger with default settings:

```r
logger <- Logger$new()
```

### Logging Messages

The `Logger` class provides three methods for logging messages at different levels:

```r
logger$info("This is an informational message")
logger$warn("This is a warning message")
logger$error("This is an error message")
```

### Changing Log Level

You can change the minimum log level:

```r
logger$set_level(LogLevel$WARNING)
# Now, info messages won't be logged
logger$info("This won't be logged")
logger$warn("But this will be")
```

## Advanced Usage

### Custom Print Function

You can customize how messages are printed by providing a custom print function:

```r
custom_logger <- Logger$new(
    print_fn = function(x) cat(crayon::bold(x), "\n")
)
custom_logger$info("This will be printed in bold")
```

### Logging to a File

To save logs to a file, specify a file path when creating the logger:

```r
file_logger <- Logger$new(file_path = "app.log")
file_logger$info("This message will be saved to app.log")
```

### Including Additional Data

You can include additional data with your log messages:

```r
logger$info("Operation completed", data = list(duration = 5.2, status = "success"))
```

### Logging Errors

When logging errors, you can include the error object:

```r
tryCatch(
    stop("An error occurred"),
    error = function(e) {
        logger$error("Error in operation", error = e)
    }
)
```

## Helper Functions

The `Logger` package also includes some helpful utility functions:

### messageParallel

This function allows you to print messages from parallel forked processes:

```r
messageParallel("Send this message back up.")
```

### tableToString

This function converts a data.frame printout to a string, useful for including tabular data in log messages:

```r
df <- data.frame(a = 1:3, b = letters[1:3])
log_message <- paste("Current data:", tableToString(df))
logger$info(log_message)
```

### valueCoordinates

This function helps you find the coordinates of specific values in a data.frame:

```r
df <- data.frame(a = c(1, NA, 3), b = c(NA, 2, NA), c = c(3, 2, 1))
coords <- valueCoordinates(df, NA)
logger$info("Found NA values at:", data = coords)
```

## Conclusion

The `Logger` package provides a powerful and flexible logging system for R applications. By using this package, you can easily add robust logging capabilities to your projects, helping with debugging, monitoring, and maintaining your code.

For more information, please refer to the package documentation or contact the author, Dereck Mezquita.